---
- hosts: all
  gather_facts: yes
  become: true

  vars:
    prometheus_scrape_configs:
      - job_name: "prometheus"    # Custom scrape job, here using `static_config`
        metrics_path: "/metrics"
        static_configs:
          - targets:
            - "10.128.0.37:9090"
      - job_name: "example-node-file-servicediscovery"
        file_sd_configs:
          - files:
            - "{{ prometheus_config_dir }}/file_sd/node.yml" # This line loads file created from `prometheus_targets`

  roles:
    - { role: cloudalchemy.prometheus }
